spring.application.name=backend-springboot
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.threads.virtual.enabled=true
server.port=${SERVER_PORT}

room.code.length=6
room.code.charset=${ROOM_CODE_CHARSET}

#spring.mongodb.uri=mongodb://${SPRING_MONGODB_HOST}:${SPRING_MONGODB_PORT}/huddle
#spring.mongodb.host=${SPRING_MONGODB_HOST}
#spring.mongodb.port=${SPRING_MONGODB_PORT}
spring.mongodb.database=huddle

guest.user.password=${GUEST_USER_PASSWORD}
guest.user.expire.after.seconds=${GUEST_USER_EXPIRE_AFTER_SECONDS}
signaling.secret.salt=${SIGNALING_SECRET_SALT}
signaling.session.max.idle.time=${SIGNALING_SESSION_MAX_IDLE_TIME}
signaling.session.ping.rate=${SIGNALING_SESSION_PING_RATE}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

redis.channel.name=${REDIS_CHANNEL_NAME}
max.room.size=4

room.code.attempts=${ROOM_CODE_ATTEMPTS}
room.expiration.time=${ROOM_EXPIRATION_TIME}
room.expiration.time.unit=${ROOM_EXPIRATION_TIME_UNIT}

#spring.data.redis.host=${SPRING_REDIS_HOST}
#spring.data.redis.port=${SPRING_REDIS_PORT}
